name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies with uv
        run: uv sync

      - name: Run tests
        run: uv run pytest
        env:
          UV_THREADPOOL_SIZE: 4

  hatch-build-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Build package
        run: hatch build

      - name: Verify build artifacts
        shell: bash
        run: |
          echo "Generated artifacts:"
          ls -la dist
          files=$(ls -A dist | wc -l)
          if [ $files -eq 0 ]; then
            echo "Error: No artifacts generated!"
            exit 1
          fi
          echo "Found $files artifacts"
