name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.13]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies with uv
        run: uv sync

      - name: Run tests
        run: uv run pytest
        env:
          UV_THREADPOOL_SIZE: 4

  build-and-publish-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv and hatch
        run: |
          python -m pip install --upgrade pip
          pip install uv hatch

      - name: Install dependencies
        run: uv sync

      - name: Build package
        run: hatch build

      - name: Verify build artifacts
        run: |
          ls dist
          echo "Generated artifacts:"
          find dist -type f -print

      - name: Dry-run publish
        run: hatch publish --dry-run
